CREATE DATABASE DreamsTourism 

CREATE TABLE USUARIO(
	ID_CLIENTE INT PRIMARY KEY,
	ENDERECO VARCHAR(100),
	TELEFONE CHAR(14),
	CPF CHAR(15),
	CEP CHAR(9),
	EMAIL VARCHAR(100),
	ESTADO CHAR(2),
	DT_NASCIMENTO DATE, 
	COMPLEMENTO VARCHAR (90)
)

CREATE TABLE PACOTE(
	ID_PACOTE INT PRIMARY KEY,
	NOME_PACOTE VARCHAR(70),
	ID_DESTINO INT, 
	PRECO INT,
	DURACAO CHAR(2),
--	DISPONIBILIDADE_DTS
	DESCRICAO_LUGAR VARCHAR(5000),
	DESCRICAO_CARD1 VARCHAR(5000),
	DESCRICAO_CARD2 VARCHAR(5000),
	DESCRICAO_CARD3 VARCHAR(5000),
	INCLUSOS VARCHAR(200)
)

CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY, 
	ID_PACOTE INT,
	DATA_PEDIDO DATE,
	VALOR INT,
	ID_CLIENTE INT,
	CHECK_IN DATE,
	CHECK_OUT DATE,
	DATA_RESERVADA DATE
--	TIPO_PAGAMENTO
)