CREATE DATABASE DreamsTourism

USE DreamsTourism

CREATE TABLE CLIENTE(
	COD_CLIENTE INT,
	NOME VARCHAR(70) NOT NULL,
	TELEFONE CHAR(14) NOT NULL,
	CPF CHAR(11) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	ENDERECO VARCHAR(100),
	CIDADE VARCHAR(70),
	BAIRRO VARCHAR(70),
	UF CHAR(2),
	CONSTRAINT PK_COD_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE PEDIDO(
	COD_PEDIDO INT, 
	COD_PACOTE INT,
	COD_CLIENTE INT,
	DATA_PEDIDO DATE,
	VALOR INT,
	CHECK_IN DATE,
	CHECK_OUT DATE,
	DATA_RESERVADA DATE,
	TIPO_PAGAMENTO VARCHAR (50),
	CONSTRAINT PK_COD_PEDIDO PRIMARY KEY (COD_PEDIDO),
	CONSTRAINT FK_COD_PACOTE_PEDIDO FOREIGN KEY (COD_PACOTE) REFERENCES PACOTE (COD_PACOTE),
	CONSTRAINT FK_COD_CLIENTE_PEDIDO FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

CREATE TABLE PACOTE(
	COD_PACOTE INT NOT NULL,
	NOME_PACOTE VARCHAR(70), 
	PRECO INT,
	DURACAO CHAR(2),
	HOSPEDAGEM VARCHAR(150),
	INCLUSOS VARCHAR(200),
	CONSTRAINT PK_COD_PACOTE PRIMARY KEY (COD_PACOTE)
);

CREATE TABLE PACOTE_PEDIDO(
	COD_PEDIDO INT,
	COD_PACOTE INT,
	CONSTRAINT PK_PACOTE_PEDIDO PRIMARY KEY (COD_PEDIDO, COD_PACOTE),
	CONSTRAINT FK_COD_PEDIDO_PACOTE FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO),
	CONSTRAINT FK_COD_PACOTE FOREIGN KEY (COD_PACOTE) REFERENCES PACOTE (COD_PACOTE)
);

CREATE TABLE DESCRICAO(
	COD_DESCRICAO INT,
	COD_PACOTE INT,
	DESCRICAO_LUGAR VARCHAR(5000),
	CARD_ESQUERDO VARCHAR(5000),
	CARD_CENTRO VARCHAR(5000),
	CARD_DIREITO VARCHAR(5000),
	CONSTRAINT PK_ID_DESCRICAO PRIMARY KEY (COD_DESCRICAO),
	CONSTRAINT FK_COD_DESCRICAO_PACOTE FOREIGN KEY (COD_PACOTE) REFERENCES PACOTE (COD_PACOTE)
);

CREATE TABLE IMAGE(
ID INT NOT NULL,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
URLIMAGEM NVARCHAR(MAX),
CONSTRAINT PK_ID_IMAGE PRIMARY KEY (ID)
);
